# Generated by Django 4.2.2 on 2023-06-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('folder1', models.CharField(max_length=10000)),
                ('folder2', models.CharField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
