# Generated by Django 4.2.2 on 2023-06-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0002_folder_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='folder1',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='folder2',
        ),
        migrations.AddField(
            model_name='folder',
            name='file1',
            field=models.FileField(default='', max_length=50, upload_to=''),
        ),
        migrations.AddField(
            model_name='folder',
            name='file2',
            field=models.FileField(default='', max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
