# Generated by Django 3.2.19 on 2023-06-25 21:51

import Upload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0003_remove_folder_folder1_remove_folder_folder2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('file1', models.FileField(max_length=1500, upload_to=Upload.models.get_upload_path)),
            ],
        ),
        migrations.AlterField(
            model_name='folder',
            name='file1',
            field=models.FileField(max_length=150, upload_to=Upload.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='folder',
            name='file2',
            field=models.FileField(max_length=150, upload_to=Upload.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
